#!/usr/bin/env bash
# This script configures an Ubuntu server host file ips
cp /etc/hosts ~/hosts.new
IP='127.0.0.2'
HOST="localhost"
IP2='8.8.8.8'
HOST2="facebook.com"
HOSTS_LINE="$IP2\t$HOST2"
sudo -- sh -c -e "echo '$HOSTS_LINE' >> /etc/hosts";

sed -i "/$HOST/ s/.*/$IP\t$HOST/g" ~/hosts.new
cp -f ~/hosts.new /etc/hosts
