#!/usr/bin/env bash
# This script configures an Ubuntu server host file ips
cp /etc/hosts ~/hosts.new
sed -i s/^127.0.0.1/127.0.0.2/ ~/hosts.new
echo "8.8.8.8\tfacebook.com"
cp -f ~/hosts.new /etc/hosts
